language: python
python:
  - 3.6
services:
  - docker
install:
  - docker build -t max-image-completer .
  - docker run -it -d -p 5000:5000 max-image-completer
  - sleep 30
before_script:
  - pip install pytest requests pillow
script:
  - pytest tests/test.py
